spring:
  application:
    name: eagle-bank-api
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      hibernate:
        format_sql: true
        jdbc:
          lob:
            non_contextual_creation: true
    show-sql: false
    open-in-view: false

server:
  port: 8080
  servlet:
    context-path: /api

jwt:
  secret: ${JWT_SECRET:your-secret-key-change-in-production}
  expiration: 86400000 # 24 hours in milliseconds

logging:
  level:
    com.eaglebank: DEBUG
    org.springframework.web: INFO
    org.springframework.security: DEBUG

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
    enabled: true
    tryItOutEnabled: true
    filter: true
    operationsSorter: method
    tagsSorter: alpha
    displayRequestDuration: true
  show-actuator: false