global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    monitor: 'eaglebank-monitor'

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'eaglebank-api'
    metrics_path: '/api/actuator/prometheus'
    static_configs:
      - targets: ['app:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'eaglebank-api'